//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurakin_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        public int id { get; set; }
        public int guest_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime checkIn { get; set; }
        public System.DateTime checkOut { get; set; }
    
        public virtual guests guests { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
